"""empty message

Revision ID: 9b6c37f94219
Revises: 2cfd97156683
Create Date: 2021-06-01 15:39:39.386525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b6c37f94219'
down_revision = '2cfd97156683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_picture')
    # ### end Alembic commands ###
